name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        shell: pwsh
        run: |
          $env:CXXFLAGS = "/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"
          flutter build windows --release

      - name: Compress
        shell: pwsh
        run: |
          $releasePath = "build\windows\x64\runner\Release"
          if (-not (Test-Path $releasePath)) {
            $releasePath = "build\windows\runner\Release"
          }
          Compress-Archive -Path "$releasePath\*" -DestinationPath "LolPlusTV-Windows.zip" -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LolPlusTV-Windows
          path: LolPlusTV-Windows.zip
          retention-days: 15
